version: "3.9"

# Per-node deployment stack (run on each VPN node host)
services:
  node-agent:
    build:
      context: .
      dockerfile: deploy/node-agent.Dockerfile
    container_name: node_agent
    privileged: true
    environment:
      - NODE_ID=${NODE_ID}
      - NODE_NAME=${NODE_NAME}
      - NODE_TAGS=${NODE_TAGS}
      - CONTROL_PLANE_GRPC_ADDRESS=${CONTROL_PLANE_GRPC_ADDRESS}
      - SAMPLE_INTERVAL_SECONDS=${SAMPLE_INTERVAL_SECONDS:-60}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./certs/nodes:/certs/nodes:ro
      - ./certs/ca:/certs/ca:ro
      - /var/run/xray:/var/run/xray
      - /etc/xray:/etc/xray
    network_mode: host  # access to wg + xray local ports
    depends_on:
      - xray

  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    volumes:
      - /etc/xray:/etc/xray
      - /var/run/xray:/var/run/xray
    network_mode: host

  # WireGuard runs on host kernel; we only need the tools present (node-agent).

networks: {}

